use std::collections::HashMap;
use std::fs;
use std::path::Path;

use anyhow::{Context, Result};
use clap::Parser;
use regex::Regex;

mod format;
use format::InstructionFormat;

#[derive(Parser, Debug)]
#[command(author, version, about, long_about = None)]
struct Args {
    /// Path to the loongarch_opcodes directory
    #[arg(short, long)]
    input_dir: String,

    /// Output file path
    #[arg(short, long, default_value = "loongarchdata.rs")]
    output: String,
}

#[derive(Debug)]
struct Instruction {
    opcode: u32,
    mnemonic: String,
    format: InstructionFormat,
    comment: Option<String>,
    is_64bit: bool,
    extensions: Vec<String>,
}

fn main() -> Result<()> {
    let args = Args::parse();

    // Parse all instruction files
    let instructions = parse_instructions(&args.input_dir)?;

    // Generate Rust code
    let code = generate_code(&instructions)?;

    // Write output
    fs::write(&args.output, code)?;

    println!("Successfully generated {}", args.output);
    Ok(())
}

fn parse_instructions(input_dir: &str) -> Result<Vec<Instruction>> {
    let dir = Path::new(input_dir);
    let mut instructions = Vec::new();

    // Regex to match instruction lines
    let re = Regex::new(r"^(?P<opcode>[0-9a-f]+)\s+(?P<mnemonic>\w+)\s+(?P<format>\w+)(?:\s+@(?P<comment>.*))?$")?;

    // Read all .txt files in the directory
    for entry in fs::read_dir(dir)? {
        let entry = entry?;
        let path = entry.path();
        if path.extension().map_or(false, |ext| ext == "txt") {
            let filename = path.file_name().unwrap().to_string_lossy();
            let is_64bit = filename.contains("64");
            let mut extensions = Vec::new();
            
            // Determine extensions from filename
            if filename.contains("base") {
                extensions.push("Ex_BASE".to_string());
            }
            if filename.contains("fp") {
                if filename.contains("-d") {
                    extensions.push("Ex_D".to_string());
                } else {
                    extensions.push("Ex_F".to_string());
                }
            }
            if filename.contains("atomics") {
                extensions.push("Ex_BASE".to_string());
            }
            if filename == "lsx.txt" {
                extensions.push("Ex_LSX".to_string());
            }
            if filename == "lasx.txt" {
                extensions.push("Ex_LASX".to_string());
            }
            if filename == "lvz.txt" {
                extensions.push("Ex_LVZ".to_string());
            }
            if filename == "lbt.txt" {
                extensions.push("Ex_LBT".to_string());
            }
            if filename.contains("privileged") {
                extensions.push("Ex_PRIV".to_string());
            }

            let content = fs::read_to_string(&path)?;
            for line in content.lines() {
                if line.trim().is_empty() || line.starts_with('#') {
                    continue;
                }

                if let Some(caps) = re.captures(line) {
                    let opcode = u32::from_str_radix(&caps["opcode"], 16)
                        .with_context(|| format!("Invalid opcode: {}", &caps["opcode"]))?;
                    
                    if let Some(format) = InstructionFormat::parse(&caps["format"], opcode) {
                        instructions.push(Instruction {
                            opcode,
                            mnemonic: caps["mnemonic"].to_string(),
                            format,
                            comment: caps.name("comment").map(|m| m.as_str().trim().to_string()),
                            is_64bit,
                            extensions: extensions.clone(),
                        });
                    }
                }
            }
        }
    }

    Ok(instructions)
}

fn generate_code(instructions: &[Instruction]) -> Result<String> {
    let mut code = String::new();

    // Generate header
    code.push_str("// Auto-generated by loongarch_codegen\n");
    code.push_str("use super::Template;\n");
    code.push_str("use super::Command;\n");
    code.push_str("use super::Matcher;\n");
    code.push_str("use super::Relocation;\n");
    code.push_str("use super::{ISAFlags, ExtensionFlags};\n\n");

    // Generate instruction definitions
    code.push_str("lazy_static! {\n");
    code.push_str("    static ref OPMAP: HashMap<&'static str, &'static [Opdata]> = {\n");
    code.push_str("        #![allow(non_upper_case_globals)]\n\n");
    code.push_str("        const LA32: u8 = ISAFlags::LA32.bits();\n");
    code.push_str("        const LA64: u8 = ISAFlags::LA64.bits();\n\n");
    code.push_str("        const Ex_BASE: u64 = ExtensionFlags::Ex_BASE.bits();\n");
    code.push_str("        const Ex_BIT: u64 = ExtensionFlags::Ex_BIT.bits();\n");
    code.push_str("        const Ex_F: u64 = ExtensionFlags::Ex_F.bits();\n");
    code.push_str("        const Ex_D: u64 = ExtensionFlags::Ex_D.bits();\n");
    code.push_str("        const Ex_LSX: u64 = ExtensionFlags::Ex_LSX.bits();\n");
    code.push_str("        const Ex_LASX: u64 = ExtensionFlags::Ex_LASX.bits();\n");
    code.push_str("        const Ex_LVZ: u64 = ExtensionFlags::Ex_LVZ.bits();\n");
    code.push_str("        const Ex_LBT: u64 = ExtensionFlags::Ex_LBT.bits();\n");
    code.push_str("        const Ex_PRIV: u64 = ExtensionFlags::Ex_PRIV.bits();\n\n");

    // Group instructions by mnemonic
    let mut grouped: HashMap<&str, Vec<&Instruction>> = HashMap::new();
    for inst in instructions {
        grouped.entry(&inst.mnemonic).or_default().push(inst);
    }

    code.push_str("        static MAP: &[(&str, &[Opdata])] = &[\n");

    // Generate instruction entries
    for (mnemonic, insts) in grouped {
        code.push_str(&format!("            (\"{}\", &[\n", mnemonic));

        for inst in insts {
            // Generate ISA flags
            let isa_flags = if inst.is_64bit {
                "LA64"
            } else {
                "LA32"
            };

            // Generate extension flags
            let ext_flags = inst.extensions.join(" | ");

            // Generate matchers
            let matchers = inst.format.generate_matchers()
                .iter()
                .map(|m| m.as_str())
                .collect::<Vec<_>>()
                .join(", ");

            // Generate commands
            let commands = inst.format.generate_commands()
                .iter()
                .map(|c| c.as_str())
                .collect::<Vec<_>>()
                .join(", ");

            // Generate instruction entry
            code.push_str(&format!(r#"                SingleOp!(
                    Template::Single(0x{:08x}),
                    {},
                    [ {} ],
                    [ {} ],
                    [ {} ]
                ),
"#, inst.opcode, isa_flags, matchers, commands, ext_flags));
        }

        code.push_str("            ]),\n");
    }

    code.push_str("        ];\n");
    code.push_str("        MAP.iter().cloned().collect()\n");
    code.push_str("    };\n");
    code.push_str("}\n");

    Ok(code)
}