// Auto-generated by loongarch_codegen
use super::Template;
use super::Command;
use super::Matcher;
use super::Relocation;
use super::{ISAFlags, ExtensionFlags};

lazy_static! {
    static ref OPMAP: HashMap<&'static str, &'static [Opdata]> = {
        #![allow(non_upper_case_globals)]

        const LA32: u8 = ISAFlags::LA32.bits();
        const LA64: u8 = ISAFlags::LA64.bits();

        const Ex_BASE: u64 = ExtensionFlags::Ex_BASE.bits();
        const Ex_BIT: u64 = ExtensionFlags::Ex_BIT.bits();
        const Ex_F: u64 = ExtensionFlags::Ex_F.bits();
        const Ex_D: u64 = ExtensionFlags::Ex_D.bits();
        const Ex_LSX: u64 = ExtensionFlags::Ex_LSX.bits();
        const Ex_LASX: u64 = ExtensionFlags::Ex_LASX.bits();
        const Ex_LVZ: u64 = ExtensionFlags::Ex_LVZ.bits();
        const Ex_LBT: u64 = ExtensionFlags::Ex_LBT.bits();
        const Ex_PRIV: u64 = ExtensionFlags::Ex_PRIV.bits();

        static MAP: &[(&str, &[Opdata])] = &[
            ("gtlbclr", &[
                SingleOp!(
                    Template::Single(0x06482001),
                    LA32,
                    [  ],
                    [  ],
                    [ Ex_LVZ ]
                ),
            ]),
            ("andi", &[
                SingleOp!(
                    Template::Single(0x03400000),
                    LA32,
                    [ Matcher::R, Matcher::R, Matcher::Imm ],
                    [ Command::R(0), Command::R(5), Command::UImm(12, 0) ],
                    [ Ex_BASE ]
                ),
            ]),
            ("x86mftop", &[
                SingleOp!(
                    Template::Single(0x00007400),
                    LA32,
                    [ Matcher::R ],
                    [ Command::R(0) ],
                    [ Ex_LBT ]
                ),
            ]),
            ("movgr2scr", &[
                SingleOp!(
                    Template::Single(0x00000800),
                    LA32,
                    [ Matcher::R ],
                    [ Command::R(5) ],
                    [ Ex_LBT ]
                ),
            ]),
            ("preld", &[
                SingleOp!(
                    Template::Single(0x2ac00000),
                    LA32,
                    [ Matcher::R, Matcher::Imm ],
                    [ Command::R(5), Command::SImm(12, 0) ],
                    [ Ex_BASE ]
                ),
            ]),
            ("x86setloope", &[
                SingleOp!(
                    Template::Single(0x00007800),
                    LA32,
                    [ Matcher::R, Matcher::R ],
                    [ Command::R(0), Command::R(5) ],
                    [ Ex_LBT ]
                ),
            ]),
            ("pcaddu12i", &[
                SingleOp!(
                    Template::Single(0x1c000000),
                    LA32,
                    [ Matcher::R, Matcher::Offset ],
                    [ Command::R(0), Command::Offset(Relocation::J) ],
                    [ Ex_BASE ]
                ),
            ]),
            ("xvstx", &[
                SingleOp!(
                    Template::Single(0x384c0000),
                    LA32,
                    [ Matcher::R, Matcher::R ],
                    [ Command::R(5), Command::R(10) ],
                    [ Ex_LASX ]
                ),
            ]),
            ("eret", &[
                SingleOp!(
                    Template::Single(0x06483800),
                    LA32,
                    [  ],
                    [  ],
                    [ Ex_PRIV ]
                ),
            ]),
            ("jiscr0", &[
                SingleOp!(
                    Template::Single(0x48000200),
                    LA32,
                    [ Matcher::Imm ],
                    [ Command::SImm(16, 0) ],
                    [ Ex_LBT ]
                ),
            ]),
            ("x86setloopne", &[
                SingleOp!(
                    Template::Single(0x00007c00),
                    LA32,
                    [ Matcher::R, Matcher::R ],
                    [ Command::R(0), Command::R(5) ],
                    [ Ex_LBT ]
                ),
            ]),
            ("tlbfill", &[
                SingleOp!(
                    Template::Single(0x06483400),
                    LA32,
                    [  ],
                    [  ],
                    [ Ex_PRIV ]
                ),
            ]),
            ("cpucfg", &[
                SingleOp!(
                    Template::Single(0x00006c00),
                    LA32,
                    [ Matcher::R, Matcher::R ],
                    [ Command::R(0), Command::R(5) ],
                    [ Ex_BASE ]
                ),
            ]),
            ("fcsrwr", &[
                SingleOp!(
                    Template::Single(0x0114c000),
                    LA32,
                    [ Matcher::R ],
                    [ Command::R(5) ],
                    [ Ex_F ]
                ),
            ]),
            ("ibar", &[
                SingleOp!(
                    Template::Single(0x38728000),
                    LA32,
                    [  ],
                    [  ],
                    [ Ex_BASE ]
                ),
            ]),
            ("tlbwr", &[
                SingleOp!(
                    Template::Single(0x06483000),
                    LA32,
                    [  ],
                    [  ],
                    [ Ex_PRIV ]
                ),
            ]),
            ("vldx", &[
                SingleOp!(
                    Template::Single(0x38400000),
                    LA32,
                    [ Matcher::V, Matcher::R, Matcher::R ],
                    [ Command::V(0), Command::R(5), Command::R(10) ],
                    [ Ex_LSX ]
                ),
            ]),
            ("bgtu", &[
                SingleOp!(
                    Template::Single(0x68000000),
                    LA32,
                    [ Matcher::R, Matcher::R, Matcher::Imm ],
                    [ Command::R(0), Command::R(5), Command::SImm(16, 0) ],
                    [ Ex_BASE ]
                ),
            ]),
            ("gtlbsrch", &[
                SingleOp!(
                    Template::Single(0x06482801),
                    LA32,
                    [  ],
                    [  ],
                    [ Ex_LVZ ]
                ),
            ]),
            ("and", &[
                SingleOp!(
                    Template::Single(0x00148000),
                    LA32,
                    [ Matcher::R, Matcher::R, Matcher::R ],
                    [ Command::R(0), Command::R(5), Command::R(10) ],
                    [ Ex_BASE ]
                ),
            ]),
            ("masknez", &[
                SingleOp!(
                    Template::Single(0x00138000),
                    LA32,
                    [ Matcher::R, Matcher::R, Matcher::R ],
                    [ Command::R(0), Command::R(5), Command::R(10) ],
                    [ Ex_BASE ]
                ),
            ]),
            ("sltui", &[
                SingleOp!(
                    Template::Single(0x02400000),
                    LA32,
                    [ Matcher::R, Matcher::R, Matcher::Imm ],
                    [ Command::R(0), Command::R(5), Command::SImm(12, 0) ],
                    [ Ex_BASE ]
                ),
            ]),
            ("gtlbwr", &[
                SingleOp!(
                    Template::Single(0x06483001),
                    LA32,
                    [  ],
                    [  ],
                    [ Ex_LVZ ]
                ),
            ]),
            ("tlbflush", &[
                SingleOp!(
                    Template::Single(0x06482400),
                    LA32,
                    [  ],
                    [  ],
                    [ Ex_PRIV ]
                ),
            ]),
            ("xori", &[
                SingleOp!(
                    Template::Single(0x03c00000),
                    LA32,
                    [ Matcher::R, Matcher::R, Matcher::Imm ],
                    [ Command::R(0), Command::R(5), Command::UImm(12, 0) ],
                    [ Ex_BASE ]
                ),
            ]),
            ("pcalau12i", &[
                SingleOp!(
                    Template::Single(0x1a000000),
                    LA32,
                    [ Matcher::R, Matcher::Offset ],
                    [ Command::R(0), Command::Offset(Relocation::J) ],
                    [ Ex_BASE ]
                ),
            ]),
            ("beqz", &[
                SingleOp!(
                    Template::Single(0x40000000),
                    LA32,
                    [ Matcher::R, Matcher::Imm ],
                    [ Command::R(5), Command::SImm(16, 0) ],
                    [ Ex_BASE ]
                ),
            ]),
            ("jirl", &[
                SingleOp!(
                    Template::Single(0x4c000000),
                    LA32,
                    [ Matcher::R, Matcher::R, Matcher::Imm ],
                    [ Command::R(0), Command::R(5), Command::SImm(16, 0) ],
                    [ Ex_BASE ]
                ),
            ]),
            ("cacop", &[
                SingleOp!(
                    Template::Single(0x06000000),
                    LA32,
                    [ Matcher::R, Matcher::Imm ],
                    [ Command::R(5), Command::SImm(12, 0) ],
                    [ Ex_PRIV ]
                ),
            ]),
            ("slt", &[
                SingleOp!(
                    Template::Single(0x00120000),
                    LA32,
                    [ Matcher::R, Matcher::R, Matcher::R ],
                    [ Command::R(0), Command::R(5), Command::R(10) ],
                    [ Ex_BASE ]
                ),
            ]),
            ("vldi", &[
                SingleOp!(
                    Template::Single(0x73e00000),
                    LA32,
                    [ Matcher::V ],
                    [ Command::V(0) ],
                    [ Ex_LSX ]
                ),
            ]),
            ("maskeqz", &[
                SingleOp!(
                    Template::Single(0x00130000),
                    LA32,
                    [ Matcher::R, Matcher::R, Matcher::R ],
                    [ Command::R(0), Command::R(5), Command::R(10) ],
                    [ Ex_BASE ]
                ),
            ]),
            ("tlbinv", &[
                SingleOp!(
                    Template::Single(0x06498000),
                    LA32,
                    [ Matcher::R, Matcher::R ],
                    [ Command::R(5), Command::R(10) ],
                    [ Ex_PRIV ]
                ),
            ]),
            ("gtlbflush", &[
                SingleOp!(
                    Template::Single(0x06482401),
                    LA32,
                    [  ],
                    [  ],
                    [ Ex_LVZ ]
                ),
            ]),
            ("dbar", &[
                SingleOp!(
                    Template::Single(0x38720000),
                    LA32,
                    [  ],
                    [  ],
                    [ Ex_BASE ]
                ),
            ]),
            ("gtlbrd", &[
                SingleOp!(
                    Template::Single(0x06482c01),
                    LA32,
                    [  ],
                    [  ],
                    [ Ex_LVZ ]
                ),
            ]),
            ("break", &[
                SingleOp!(
                    Template::Single(0x002a0000),
                    LA32,
                    [  ],
                    [  ],
                    [ Ex_BASE ]
                ),
            ]),
            ("gtlbfill", &[
                SingleOp!(
                    Template::Single(0x06483401),
                    LA32,
                    [  ],
                    [  ],
                    [ Ex_LVZ ]
                ),
            ]),
            ("x86mttop", &[
                SingleOp!(
                    Template::Single(0x00007000),
                    LA32,
                    [  ],
                    [  ],
                    [ Ex_LBT ]
                ),
            ]),
            ("movfcc2fr", &[
                SingleOp!(
                    Template::Single(0x0114d400),
                    LA32,
                    [ Matcher::F ],
                    [ Command::F(0) ],
                    [ Ex_F ]
                ),
            ]),
            ("jiscr1", &[
                SingleOp!(
                    Template::Single(0x48000300),
                    LA32,
                    [ Matcher::Imm ],
                    [ Command::SImm(16, 0) ],
                    [ Ex_LBT ]
                ),
            ]),
            ("bne", &[
                SingleOp!(
                    Template::Single(0x5c000000),
                    LA32,
                    [ Matcher::R, Matcher::R, Matcher::Imm ],
                    [ Command::R(0), Command::R(5), Command::SImm(16, 0) ],
                    [ Ex_BASE ]
                ),
            ]),
            ("vstx", &[
                SingleOp!(
                    Template::Single(0x38440000),
                    LA32,
                    [ Matcher::V, Matcher::R, Matcher::R ],
                    [ Command::V(0), Command::R(5), Command::R(10) ],
                    [ Ex_LSX ]
                ),
            ]),
            ("nor", &[
                SingleOp!(
                    Template::Single(0x00140000),
                    LA32,
                    [ Matcher::R, Matcher::R, Matcher::R ],
                    [ Command::R(0), Command::R(5), Command::R(10) ],
                    [ Ex_BASE ]
                ),
            ]),
            ("preldx", &[
                SingleOp!(
                    Template::Single(0x382c0000),
                    LA32,
                    [ Matcher::R, Matcher::R ],
                    [ Command::R(5), Command::R(10) ],
                    [ Ex_BASE ]
                ),
            ]),
            ("xor", &[
                SingleOp!(
                    Template::Single(0x00158000),
                    LA32,
                    [ Matcher::R, Matcher::R, Matcher::R ],
                    [ Command::R(0), Command::R(5), Command::R(10) ],
                    [ Ex_BASE ]
                ),
            ]),
            ("pcaddu18i", &[
                SingleOp!(
                    Template::Single(0x1e000000),
                    LA32,
                    [ Matcher::R, Matcher::Offset ],
                    [ Command::R(0), Command::Offset(Relocation::J) ],
                    [ Ex_BASE ]
                ),
            ]),
            ("movfcc2gr", &[
                SingleOp!(
                    Template::Single(0x0114dc00),
                    LA32,
                    [ Matcher::R ],
                    [ Command::R(0) ],
                    [ Ex_F ]
                ),
            ]),
            ("vld", &[
                SingleOp!(
                    Template::Single(0x2c000000),
                    LA32,
                    [ Matcher::V, Matcher::R, Matcher::Imm ],
                    [ Command::V(0), Command::R(5), Command::SImm(12, 0) ],
                    [ Ex_LSX ]
                ),
            ]),
            ("x86settm", &[
                SingleOp!(
                    Template::Single(0x00008008),
                    LA32,
                    [  ],
                    [  ],
                    [ Ex_LBT ]
                ),
            ]),
            ("x86dectop", &[
                SingleOp!(
                    Template::Single(0x00008029),
                    LA32,
                    [  ],
                    [  ],
                    [ Ex_LBT ]
                ),
            ]),
            ("asrtle", &[
                SingleOp!(
                    Template::Single(0x00010000),
                    LA32,
                    [ Matcher::R, Matcher::R ],
                    [ Command::R(5), Command::R(10) ],
                    [  ]
                ),
            ]),
            ("bceqz", &[
                SingleOp!(
                    Template::Single(0x48000000),
                    LA32,
                    [ Matcher::Imm ],
                    [ Command::SImm(16, 0) ],
                    [ Ex_F ]
                ),
            ]),
            ("tlbclr", &[
                SingleOp!(
                    Template::Single(0x06482000),
                    LA32,
                    [  ],
                    [  ],
                    [ Ex_PRIV ]
                ),
            ]),
            ("orn", &[
                SingleOp!(
                    Template::Single(0x00160000),
                    LA32,
                    [ Matcher::R, Matcher::R, Matcher::R ],
                    [ Command::R(0), Command::R(5), Command::R(10) ],
                    [ Ex_BASE ]
                ),
            ]),
            ("bleu", &[
                SingleOp!(
                    Template::Single(0x6c000000),
                    LA32,
                    [ Matcher::R, Matcher::R, Matcher::Imm ],
                    [ Command::R(0), Command::R(5), Command::SImm(16, 0) ],
                    [ Ex_BASE ]
                ),
            ]),
            ("hypcall", &[
                SingleOp!(
                    Template::Single(0x002b8000),
                    LA32,
                    [  ],
                    [  ],
                    [ Ex_LVZ ]
                ),
            ]),
            ("asrtgt", &[
                SingleOp!(
                    Template::Single(0x00018000),
                    LA32,
                    [ Matcher::R, Matcher::R ],
                    [ Command::R(5), Command::R(10) ],
                    [  ]
                ),
            ]),
            ("gcsrxchg", &[
                SingleOp!(
                    Template::Single(0x05000000),
                    LA32,
                    [ Matcher::R, Matcher::R, Matcher::Imm ],
                    [ Command::R(0), Command::R(5), Command::SImm(14, 0) ],
                    [ Ex_LVZ ]
                ),
            ]),
            ("movfr2fcc", &[
                SingleOp!(
                    Template::Single(0x0114d000),
                    LA32,
                    [ Matcher::F ],
                    [ Command::F(0) ],
                    [ Ex_F ]
                ),
            ]),
            ("bcnez", &[
                SingleOp!(
                    Template::Single(0x48000100),
                    LA32,
                    [ Matcher::Imm ],
                    [ Command::SImm(16, 0) ],
                    [ Ex_F ]
                ),
            ]),
            ("csrxchg", &[
                SingleOp!(
                    Template::Single(0x04000000),
                    LA32,
                    [ Matcher::R, Matcher::R, Matcher::Imm ],
                    [ Command::R(0), Command::R(5), Command::SImm(14, 0) ],
                    [ Ex_PRIV ]
                ),
            ]),
            ("slti", &[
                SingleOp!(
                    Template::Single(0x02000000),
                    LA32,
                    [ Matcher::R, Matcher::R, Matcher::Imm ],
                    [ Command::R(0), Command::R(5), Command::SImm(12, 0) ],
                    [ Ex_BASE ]
                ),
            ]),
            ("xvld", &[
                SingleOp!(
                    Template::Single(0x2c800000),
                    LA32,
                    [ Matcher::R, Matcher::Imm ],
                    [ Command::R(5), Command::SImm(12, 0) ],
                    [ Ex_LASX ]
                ),
            ]),
            ("tlbrd", &[
                SingleOp!(
                    Template::Single(0x06482c00),
                    LA32,
                    [  ],
                    [  ],
                    [ Ex_PRIV ]
                ),
            ]),
            ("dbgcall", &[
                SingleOp!(
                    Template::Single(0x002a8000),
                    LA32,
                    [  ],
                    [  ],
                    [ Ex_BASE ]
                ),
            ]),
            ("movgr2fcc", &[
                SingleOp!(
                    Template::Single(0x0114d800),
                    LA32,
                    [ Matcher::R ],
                    [ Command::R(5) ],
                    [ Ex_F ]
                ),
            ]),
            ("ori", &[
                SingleOp!(
                    Template::Single(0x03800000),
                    LA32,
                    [ Matcher::R, Matcher::R, Matcher::Imm ],
                    [ Command::R(0), Command::R(5), Command::UImm(12, 0) ],
                    [ Ex_BASE ]
                ),
            ]),
            ("bnez", &[
                SingleOp!(
                    Template::Single(0x44000000),
                    LA32,
                    [ Matcher::R, Matcher::Imm ],
                    [ Command::R(5), Command::SImm(16, 0) ],
                    [ Ex_BASE ]
                ),
            ]),
            ("tlbsrch", &[
                SingleOp!(
                    Template::Single(0x06482800),
                    LA32,
                    [  ],
                    [  ],
                    [ Ex_PRIV ]
                ),
            ]),
            ("syscall", &[
                SingleOp!(
                    Template::Single(0x002b0000),
                    LA32,
                    [  ],
                    [  ],
                    [ Ex_BASE ]
                ),
            ]),
            ("pcaddu2i", &[
                SingleOp!(
                    Template::Single(0x18000000),
                    LA32,
                    [ Matcher::R, Matcher::Offset ],
                    [ Command::R(0), Command::Offset(Relocation::J) ],
                    [ Ex_BASE ]
                ),
            ]),
            ("idle", &[
                SingleOp!(
                    Template::Single(0x06488000),
                    LA32,
                    [  ],
                    [  ],
                    [ Ex_PRIV ]
                ),
            ]),
            ("xvst", &[
                SingleOp!(
                    Template::Single(0x2cc00000),
                    LA32,
                    [ Matcher::R, Matcher::Imm ],
                    [ Command::R(5), Command::SImm(12, 0) ],
                    [ Ex_LASX ]
                ),
            ]),
            ("ble", &[
                SingleOp!(
                    Template::Single(0x64000000),
                    LA32,
                    [ Matcher::R, Matcher::R, Matcher::Imm ],
                    [ Command::R(0), Command::R(5), Command::SImm(16, 0) ],
                    [ Ex_BASE ]
                ),
            ]),
            ("xvldi", &[
                SingleOp!(
                    Template::Single(0x77e00000),
                    LA32,
                    [  ],
                    [  ],
                    [ Ex_LASX ]
                ),
            ]),
            ("bl", &[
                SingleOp!(
                    Template::Single(0x54000000),
                    LA32,
                    [ Matcher::Imm ],
                    [ Command::SImm(16, 0) ],
                    [ Ex_BASE ]
                ),
            ]),
            ("or", &[
                SingleOp!(
                    Template::Single(0x00150000),
                    LA32,
                    [ Matcher::R, Matcher::R, Matcher::R ],
                    [ Command::R(0), Command::R(5), Command::R(10) ],
                    [ Ex_BASE ]
                ),
            ]),
            ("beq", &[
                SingleOp!(
                    Template::Single(0x58000000),
                    LA32,
                    [ Matcher::R, Matcher::R, Matcher::Imm ],
                    [ Command::R(0), Command::R(5), Command::SImm(16, 0) ],
                    [ Ex_BASE ]
                ),
            ]),
            ("bgt", &[
                SingleOp!(
                    Template::Single(0x60000000),
                    LA32,
                    [ Matcher::R, Matcher::R, Matcher::Imm ],
                    [ Command::R(0), Command::R(5), Command::SImm(16, 0) ],
                    [ Ex_BASE ]
                ),
            ]),
            ("movscr2gr", &[
                SingleOp!(
                    Template::Single(0x00000c00),
                    LA32,
                    [ Matcher::R ],
                    [ Command::R(0) ],
                    [ Ex_LBT ]
                ),
            ]),
            ("x86inctop", &[
                SingleOp!(
                    Template::Single(0x00008009),
                    LA32,
                    [  ],
                    [  ],
                    [ Ex_LBT ]
                ),
            ]),
            ("x86clrtm", &[
                SingleOp!(
                    Template::Single(0x00008028),
                    LA32,
                    [  ],
                    [  ],
                    [ Ex_LBT ]
                ),
            ]),
            ("sltu", &[
                SingleOp!(
                    Template::Single(0x00128000),
                    LA32,
                    [ Matcher::R, Matcher::R, Matcher::R ],
                    [ Command::R(0), Command::R(5), Command::R(10) ],
                    [ Ex_BASE ]
                ),
            ]),
            ("fcsrrd", &[
                SingleOp!(
                    Template::Single(0x0114c800),
                    LA32,
                    [ Matcher::R ],
                    [ Command::R(0) ],
                    [ Ex_F ]
                ),
            ]),
            ("vst", &[
                SingleOp!(
                    Template::Single(0x2c400000),
                    LA32,
                    [ Matcher::V, Matcher::R, Matcher::Imm ],
                    [ Command::V(0), Command::R(5), Command::SImm(12, 0) ],
                    [ Ex_LSX ]
                ),
            ]),
            ("andn", &[
                SingleOp!(
                    Template::Single(0x00168000),
                    LA32,
                    [ Matcher::R, Matcher::R, Matcher::R ],
                    [ Command::R(0), Command::R(5), Command::R(10) ],
                    [ Ex_BASE ]
                ),
            ]),
            ("b", &[
                SingleOp!(
                    Template::Single(0x50000000),
                    LA32,
                    [ Matcher::Imm ],
                    [ Command::SImm(16, 0) ],
                    [ Ex_BASE ]
                ),
            ]),
            ("xvldx", &[
                SingleOp!(
                    Template::Single(0x38480000),
                    LA32,
                    [ Matcher::R, Matcher::R ],
                    [ Command::R(5), Command::R(10) ],
                    [ Ex_LASX ]
                ),
            ]),
        ];
        MAP.iter().cloned().collect()
    };
}
