//! This file contains the datastructure specification for the LoongArch encoding data
use bitflags::bitflags;
use lazy_static::lazy_static;
use std::collections::{HashMap, hash_map};
use super::ast::RegId;
use std::fmt;

/// A template contains the information for the static parts of an instruction encoding, as well
/// as its bitsize and length
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Template {
    /// A single 32-bit instruction
    Single(u32),
    // Two 32-bit instructions. Used for load/store reg, offset
    Double(u32, u32),
    // / A long instruction sequence. Used to load big immediates.
    Many(&'static [u32])
}


bitflags! {
    /// Flags indicating what ISA targets an instruction is valid on
    #[derive(Debug, Clone, Copy)]
    pub struct ISAFlags: u8 {
        const LA32 = 0x01;
        const LA64 = 0x02;
    }

    /// Flags specifying what ISA extensions are required for an instruction
    #[derive(Debug, Clone, Copy)]
    pub struct ExtensionFlags: u64 {
        /// Base integer instructions
        const Ex_BASE = 0x0000_0000_0000_0001;
        /// Bit manipulation instructions
        const Ex_BIT = 0x0000_0000_0000_0002;
        /// Single-precision floating-point
        const Ex_F = 0x0000_0000_0000_0004;
        /// Double-precision floating-point
        const Ex_D = 0x0000_0000_0000_0008;
        /// SIMD instructions (LSX)
        const Ex_LSX = 0x0000_0000_0000_0010;
        /// Advanced SIMD instructions (LASX)
        const Ex_LASX = 0x0000_0000_0000_0020;
        /// Virtual instructions (LVZ)
        const Ex_LVZ = 0x0000_0000_0000_0040;
        /// Binary translation instructions (LBT)
        const Ex_LBT = 0x0000_0000_0000_0080;
        /// Privileged instructions
        const Ex_PRIV = 0x0000_0000_0000_0100;
    }
}

impl ISAFlags {
    const fn make(bits: u8) -> ISAFlags {
        ISAFlags::from_bits_truncate(bits)
    }
}

impl ExtensionFlags {
    const fn make(bits: u64) -> ExtensionFlags {
        ExtensionFlags::from_bits_truncate(bits)
    }
}

impl fmt::Display for ExtensionFlags {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        let mut first = true;
        for (flag, _) in self.iter_names() {
            if !first {
                write!(f, "_")?;
            }
            write!(f, "{}", &flag[3..])?;
            first = false;
        }
        Ok(())
    }
}

impl Default for ExtensionFlags {
    fn default() -> ExtensionFlags {
        ExtensionFlags::Ex_BASE
    }
}

/// Matchers validate the types of arguments passed to an instruction
#[derive(Debug, Clone, Copy, PartialEq)]
pub enum Matcher {
    /// A general purpose register
    R,
    /// A floating point register
    F,
    /// 条件标志寄存器
    C,
    /// fcsr
    FCSR,
    /// A scratch register
    T,
    /// A LAX register
    V,
    /// A LASX register
    X,
    /// A specific register
    Reg(RegId),
    /// An indirect reference to a register
    Ref,
    /// An indirect reference with offset. expands args to X, Imm
    RefOffset,
    /// An pc-relative indirect reference. The register ought to contain an address
    /// generated by AUIPC for the same label
    RefLabel,
    /// An immediate value
    Imm,
    /// A jump offset
    Offset,
    /// An identifier
    Ident,
}

/// Encoding commands specify how arguments should be encoded
#[derive(Debug, Clone)]
pub enum Command {
    // Meta commands
    /// Repeat the same argument again
    Repeat,
    /// Go to next argument
    Next,

    // Register fields
    /// A 5-bit register encoding
    R(u8),
    /// A 5-bit register encoding that cannot be r0
    Rno0(u8),
    /// A 5-bit register encoding that diff before
    Rdiff(u8),
    /// A 5-bit floating point register encoding
    F(u8),
    /// A 3-bit floating point cond register encoding
    C(u8),
    /// A 2-bit floating point control/status register encoding
    FCSR(u8),
    /// A scratch register
    T(u8),
    /// A LAX register
    V(u8),
    /// A LASX register
    X(u8),
    // Immediate handling
    /// format: `(pos, len, shift)`
    /// `immediate >> shift` is in the range `0 .. (1 << len)`. Bottom `shift` bits are zero.
    /// `immediate >> shift` is encoded directly in a bitfield of length `len` at offset `pos`.
    Uscaled(u8, u8, u8),
    /// format: `(pos, len, shift)`
    /// `(immediate >> shift) + (1 << (len - 1))` is in the range `0 .. (1 << len)`. Bottom `shift` bits are zero.
    /// `immediate >> shift` is encoded directly in a bitfield of length `len` at offset `pos`.
    Sscaled(u8, u8, u8),
    /// format: `(pos, len)`
    /// `immediate` is in the range `1 ..= (1 << len)`.
    /// `(1 << len) - value)` is encoded in a bitfield of length `len` at offset `pos`.
    Usubone(u8, u8),
    /// Unsigned immediate: start, len
    UImm(u8, u8),
    /// format: `(pos, len)`
    /// `immediate` is in the range `1 ..= (1 << len) - prev_arg`
    /// `immediate + prev_arg - 1` is encoded in a a bitfield of length `len` at offset `pos`
    Usum(u8, u8),
    /// format: `(pos, len)`
    /// less or equal prev_arg
    /// `immediate` is in the range `0 ..= prev_arg`
    /// `immediate is encoded in a a bitfield of length `len` at offset `pos`
    Ulep(u8, u8),
    /// Signed immediate: start, len
    SImm(u8, u8),
    /// Unsigned immediate: [start, end]+
    Ufields(&'static [u8]),
    /// Signed immediate: [start, end]+
    Sfields(&'static [u8]),
    /// Jump offset
    Offset(Relocation),
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Relocation {
    // Branch instructions (beq, bne, jirl)
    // 16-bit offset, 2-bit aligned
    B = 0,
    // Branch instructions (beqz, bnez, bceqz, bcnez)
    // 21-bit offset, 2-bit aligned
    BZ = 1,
    // Jump instructions (b, bl)
    // 26-bit offset, 2-bit aligned
    J = 2,
    // PC-relative load/store
    // 32-bit offset
    PC32 = 3,

    // 20-bit offset
    SI20 = 4,
    // 14-bit offset, 2-bit aligned
    SI14 = 5,
    // 16-bit offset, 2-bit aligned
    SI16 = 6,
    // 12-bit offset,
    SI12 = 7,
    // 8-bit literal
    LITERAL8 = 9,
    // 16-bit literal
    LITERAL16 = 10,
    // 32-bit literal
    LITERAL32 = 11,
    // 64-bit literal
    LITERAL64 = 12,
}

impl Relocation {
    pub fn to_id(self) -> u8 {
        self as u8
    }

    pub fn size(self) -> u8 {
        match self {
            Relocation::LITERAL8 => 1,
            Relocation::LITERAL16 => 2,
            Relocation::B |Relocation::BZ| Relocation::J | Relocation::PC32 | 
            Relocation::LITERAL32 | Relocation::SI20 | Relocation::SI14 | Relocation::SI16 |
            Relocation::SI12 => 4,
            Relocation::LITERAL64 => 8,
        }
    }
}

#[derive(Debug, Clone, Copy)]
pub struct Opdata {
    /// The base template for the encoding
    pub template: Template,
    /// What ISA targets this op is valid for
    pub isa_flags: ISAFlags,
    /// What extensions are required for this instruction
    pub ext_flags: &'static [ExtensionFlags],
    /// Matchers for instruction arguments
    pub matchers: &'static [Matcher],
    /// Encoder commands
    pub commands: &'static [Command],
}

// macro_rules! SingleOp {
//     ( $template:expr, $isa:expr, [ $( $matcher:expr ),* ], [ $( $command:expr ),* ], [ $( $extension:expr ),* ] ) => {
//         {
//             const MATCHERS: &'static [Matcher] = {
//                 #[allow(unused_imports)]
//                 use self::Matcher::*;
//                 &[ $(
//                     $matcher
//                 ),* ]
//             };
//             const COMMANDS: &'static [Command] = {
//                 #[allow(unused_imports)]
//                 use self::Command::*;
//                 #[allow(unused_imports)]
//                 use self::Relocation::*;
//                 &[ $(
//                     $command
//                 ),* ]
//             };
//             const EXTENSIONS: &'static [ExtensionFlags] = {
//                 #[allow(unused_imports)]
//                 &[ $(
//                     ExtensionFlags::make($extension)
//                 ),* ]
//             };

//             use self::Template::*;
//             Opdata {
//                 template: $template,
//                 isa_flags: ISAFlags::make($isa),
//                 ext_flags: EXTENSIONS,
//                 matchers: MATCHERS,
//                 commands: COMMANDS,
//             }
//         }
//     }
// }

// macro_rules! Ops {
//     ( $( $name:tt = [ $( $template:expr , $isa:expr , [ $( $matcher:expr ),* ] => [ $( $command:expr ),* ] , [ $( $extension:expr ),* ] ; )+ ] , )* ) => {
//         [ $(
//             (
//                 $name,
//                 &[ $(
//                     SingleOp!( $template, $isa, [ $( $matcher ),* ], [ $( $command ),* ], [ $( $extension ),* ] )
//                 ),+ ] as &[_]
//             )
//         ),* ]
//     }
// }

macro_rules! SingleOp {
    ( $base:expr, [ $( $matcher:expr ),* ], [ $( $command:expr ),* ] ) => {
        {
            const MATCHERS: &'static [Matcher] = {
                #[allow(unused_imports)]
                use self::Matcher::*;
                &[ $(
                    $matcher
                ),* ]
            };
            const COMMANDS: &'static [Command] = {
                #[allow(unused_imports)]
                use self::Command::*;
                &[ $(
                    $command
                ),* ]
            };

            use self::Template::*;
            Opdata {
                isa_flags: ISAFlags::make(0),
                ext_flags: &[ExtensionFlags::Ex_BASE],
                template: $base,
                matchers: MATCHERS,
                commands: COMMANDS,
            }
        }
    }
}

macro_rules! Ops {
    ( $( $name:tt = [ $( $base:expr , [ $( $matcher:expr ),* ] => [ $( $command:expr ),* ] ; )+ ] )* ) => {
        [ $(
            (
                $name,
                &[ $(
                    SingleOp!( $base, [ $( $matcher ),* ], [ $( $command ),* ] )
                ),+ ] as &[_]
            )
        ),* ]
    }
}

pub fn get_mnemonic_data(name: &str) -> Option<&'static [Opdata]> {
    OPMAP.get(&name).cloned()
}

#[allow(dead_code)]
pub fn mnemonics() -> hash_map::Keys<'static, &'static str, &'static [Opdata]> {
    OPMAP.keys()
}

lazy_static! {
    static ref OPMAP: HashMap<&'static str, &'static [Opdata]> = {
        use self::Relocation::*;
        static MAP: &[(&str, &[Opdata])] = &include!("opmap.rs");
        MAP.iter().cloned().collect()
    };
}