//! This file contains the datastructure specification for the LoongArch encoding data
use bitflags::bitflags;
use lazy_static::lazy_static;
use std::collections::{HashMap, hash_map};
use super::ast::RegId;
use std::fmt;

/// A template contains the information for the static parts of an instruction encoding, as well
/// as its bitsize and length
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[allow(dead_code)] // Double/Many variants unused until multi-instruction sequences are implemented
pub enum Template {
    /// A single 32-bit instruction
    Single(u32),
    // Two 32-bit instructions. Used for load/store reg, offset
    Double(u32, u32),
    // / A long instruction sequence. Used to load big immediates.
    Many(&'static [u32])
}


bitflags! {
    /// Flags indicating what ISA targets an instruction is valid on
    #[derive(Debug, Clone, Copy)]
    pub struct ISAFlags: u8 {
        const LA32 = 0x01;
        const LA64 = 0x02;
    }

    /// Flags specifying what ISA extensions are required for an instruction
    #[derive(Debug, Clone, Copy)]
    pub struct ExtensionFlags: u64 {
        /// Base integer instructions
        const Ex_BASE = 0x0000_0000_0000_0001;
        /// Bit manipulation instructions
        const Ex_BIT = 0x0000_0000_0000_0002;
        /// Single-precision floating-point
        const Ex_F = 0x0000_0000_0000_0004;
        /// Double-precision floating-point
        const Ex_D = 0x0000_0000_0000_0008;
        /// SIMD instructions (LSX)
        const Ex_LSX = 0x0000_0000_0000_0010;
        /// Advanced SIMD instructions (LASX)
        const Ex_LASX = 0x0000_0000_0000_0020;
        /// Virtual instructions (LVZ)
        const Ex_LVZ = 0x0000_0000_0000_0040;
        /// Binary translation instructions (LBT)
        const Ex_LBT = 0x0000_0000_0000_0080;
        /// Privileged instructions
        const Ex_PRIV = 0x0000_0000_0000_0100;
    }
}

impl ISAFlags {
    #[allow(dead_code)] // make() unused until parse_features uses it (P0-4)
    const fn make(bits: u8) -> ISAFlags {
        ISAFlags::from_bits_truncate(bits)
    }
}

impl ExtensionFlags {
    #[allow(dead_code)] // make() unused until parse_features uses it (P0-4)
    const fn make(bits: u64) -> ExtensionFlags {
        ExtensionFlags::from_bits_truncate(bits)
    }
}

impl fmt::Display for ExtensionFlags {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        let mut first = true;
        for (flag, _) in self.iter_names() {
            if !first {
                write!(f, "_")?;
            }
            write!(f, "{}", &flag[3..])?;
            first = false;
        }
        Ok(())
    }
}

impl Default for ExtensionFlags {
    fn default() -> ExtensionFlags {
        ExtensionFlags::Ex_BASE
    }
}

/// Matchers validate the types of arguments passed to an instruction
#[derive(Debug, Clone, Copy, PartialEq)]
#[allow(dead_code)] // T/Reg/Ref/RefOffset/RefLabel/Ident unused until parser supports [base,offset] and label refs (P0-1)
pub enum Matcher {
    /// A general purpose register
    R,
    /// A floating point register
    F,
    /// Condition flag register
    C,
    /// fcsr
    FCSR,
    /// A scratch register
    T,
    /// A LAX register
    V,
    /// A LASX register
    X,
    /// A specific register
    Reg(RegId),
    /// An indirect reference to a register
    Ref,
    /// An indirect reference with offset. expands args to X, Imm
    RefOffset,
    /// An pc-relative indirect reference. The register ought to contain an address
    /// generated by AUIPC for the same label
    RefLabel,
    /// An immediate value
    Imm,
    /// A jump offset
    Offset,
    /// An identifier
    Ident,
}

/// Encoding commands specify how arguments should be encoded
#[allow(dead_code)] // Variants are constructed by dynasm_opmap/dynasm_extract macros (feature-gated)
#[derive(Debug, Clone)]
pub enum Command {
    // Meta commands
    /// Repeat the same argument again
    Repeat,
    /// Go to next argument
    Next,

    // Register fields
    /// A 5-bit register encoding
    R(u8),
    /// A 5-bit register encoding that cannot be r0
    Rno0(u8),
    /// A 5-bit register encoding that diff before
    Rdiff(u8),
    /// A 5-bit floating point register encoding
    F(u8),
    /// A 3-bit floating point cond register encoding
    C(u8),
    /// A 2-bit floating point control/status register encoding
    #[allow(dead_code)] // FCSR field value unused until FCSR dynamic encoding is implemented
    FCSR(u8),
    /// A scratch register
    T(u8),
    /// A LAX register
    V(u8),
    /// A LASX register
    X(u8),
    // Immediate handling
    /// format: `(pos, len, shift)`
    /// `immediate >> shift` is in the range `0 .. (1 << len)`. Bottom `shift` bits are zero.
    /// `immediate >> shift` is encoded directly in a bitfield of length `len` at offset `pos`.
    Uscaled(u8, u8, u8),
    /// format: `(pos, len, shift)`
    /// `(immediate >> shift) + (1 << (len - 1))` is in the range `0 .. (1 << len)`. Bottom `shift` bits are zero.
    /// `immediate >> shift` is encoded directly in a bitfield of length `len` at offset `pos`.
    Sscaled(u8, u8, u8),
    /// format: `(pos, len)`
    /// `immediate` is in the range `1 ..= (1 << len)`.
    /// `(1 << len) - value)` is encoded in a bitfield of length `len` at offset `pos`.
    Usubone(u8, u8),
    /// Unsigned immediate: start, len
    UImm(u8, u8),
    /// format: `(pos, len)`
    /// `immediate` is in the range `1 ..= (1 << len) - prev_arg`
    /// `immediate + prev_arg - 1` is encoded in a a bitfield of length `len` at offset `pos`
    Usum(u8, u8),
    /// format: `(pos, len)`
    /// less or equal prev_arg
    /// `immediate` is in the range `0 ..= prev_arg`
    /// `immediate is encoded in a a bitfield of length `len` at offset `pos`
    Ulep(u8, u8),
    /// Signed immediate: start, len
    SImm(u8, u8),
    /// Unsigned immediate: [start, end]+
    Ufields(&'static [u8]),
    /// Signed immediate: [start, end]+
    Sfields(&'static [u8]),
    /// Jump offset
    Offset(Relocation),
    /// Encode a slice of bits from an immediate value.
    /// format: `(offset, bits, value_offset)`
    /// Encodes `bits` bits from `value >> value_offset` at instruction bit position `offset`.
    /// The `offset` may include `+32` to target the second instruction in a Double template.
    BitRange(u8, u8, u8),
    /// Encode a slice of bits from an immediate value with rounding compensation.
    /// format: `(offset, bits, value_offset)`
    /// Adds `1 << (value_offset - 1)` to value before extracting the bits.
    /// Used for hi20 fields that need +0x800 or +0x20000 compensation.
    /// The `offset` may include `+32` to target the second instruction in a Double template.
    RBitRange(u8, u8, u8),
    /// Large immediate value (>32 bits). Declares that the immediate argument is
    /// `bitlen` bits wide, enabling BitRange/RBitRange to extract different bit ranges.
    BigImm(u8),
    /// li.w pseudo-instruction: lu12i.w + ori pair with +0x800 compensation
    /// Encodes hi20 at bits [24:5] of first inst, lo12 at bits [21:10] of second inst
    LiW32,
    /// li.d pseudo-instruction: lu12i.w + ori + lu32i.d + lu52i.d (4-instruction sequence)
    /// Encodes 64-bit immediate across 4 instructions with appropriate compensation
    LiD64,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[allow(dead_code)] // B16/LITERAL variants unused until relocation implementation is complete (P3-1/P0-3)
pub enum Relocation {
    // Branch instructions (beq, bne, jirl)
    // 16-bit offset, 2-bit aligned.
    // Per LoongArch manual: PC = PC + SignExtend({offs16, 2'b0}, GRLEN).
    // Assembly receives byte offset; value & 3 == 0 is required because
    // all LoongArch instructions are 4 bytes wide.
    B16 = 0,
    // Branch instructions (beqz, bnez, bceqz, bcnez)
    // 21-bit offset, 2-bit aligned.
    // Per LoongArch manual: PC = PC + SignExtend({offs21, 2'b0}, GRLEN).
    // Same alignment requirement as B16.
    B21 = 1,
    // Jump instructions (b, bl)
    // 26-bit offset, 2-bit aligned.
    // Per LoongArch manual: PC = PC + SignExtend({offs26, 2'b0}, GRLEN).
    // Same alignment requirement as B16.
    B26 = 2,

    // Raw 20-bit si20 field (no shift in encode).
    // Used by lu12i.w, lu32i.d for compile-time immediates.
    // The value is expected to be the already-shifted si20; the runtime
    // stores it directly into bits [24:5] without any shift.
    ABS_HI20 = 4,
    // 14-bit offset, 2-bit aligned (branch with register offset)
    // Used by ll.w, sc.w, ll.d, sc.d, ldptr.w, stptr.w, ldptr.d, stptr.d.
    SI14 = 5,
    // 12-bit signed offset (used by load/store with register + offset syntax)
    SI12 = 7,
    // PC-relative low 12 bits.
    // Encodes bits [21:10] of (label_addr - instruction_pc).
    // Used by ld.b/ld.h/ld.w/ld.d, st.b/st.h/st.w/st.d, fld.s/fld.d, fst.s/fst.d.
    PCALA_LO12 = 8,
    // PC-relative high 20 bits for pcalau12i (corresponds to ELF R_LARCH_PCALA_HI20).
    // Encodes bits [31:12] of (label_addr - instruction_pc), placed at bits [24:5].
    // Paired with PCALA_LO12 to form a full 32-bit PC-relative address load:
    //   pcalau12i $t0, :pc label   → PCALA_HI20 + PCALA_LO12
    //   addi.d    $t0, $t0, :lo label
    PCALA_HI20 = 13,
    // pcaddi: PC + SE({si20, 2'b0}). Encode shift >>2, no compensation.
    PCADD_SHIFT2 = 14,
    // pcaddu12i: PC + SE({si20, 12'b0}). Encode shift >>12, +0x800 compensation.
    PCADD_SHIFT12 = 15,
    // pcaddu18i: PC + SE({si20, 18'b0}). Encode shift >>18, +0x20000 compensation.
    PCADD_SHIFT18 = 16,
    // 8-byte SPLIT relocation: pcalau12i + addi.d pair.
    // Patches hi20 (with +0x800 compensation) into first instruction,
    // lo12 into second instruction. Used by la/la.local pseudo-instructions.
    SPLIT_PCALA = 17,
    // 8-byte SPLIT relocation: pcaddu12i + jirl pair (call30).
    // hi20 = val[31:12] at bits [24:5] of first inst (no compensation).
    // lo10 = val[11:2] at bits [25:10] of second inst (setK16).
    SPLIT_CALL30 = 18,
    // 8-byte SPLIT relocation: pcaddu18i + jirl pair (call36).
    // hi20 = (val+0x20000)[37:18] at bits [24:5] of first inst (+0x20000 compensation).
    // lo16 = val[17:2] at bits [25:10] of second inst (setK16).
    SPLIT_CALL36 = 19,
    // 8-bit literal
    LITERAL8 = 9,
    // 16-bit literal
    LITERAL16 = 10,
    // 32-bit literal
    LITERAL32 = 11,
    // 64-bit literal
    LITERAL64 = 12,
}

impl Relocation {
    /// Discriminant table used by runtime `from_encoding`.
    /// Each entry is (discriminant_value, variant_index).
    /// This const array is compiled into the proc-macro crate and
    /// provides a single source of truth that the runtime's `from_encoding`
    /// can be checked against at compile time.
    #[allow(dead_code)] // Reference table for runtime `from_encoding` consistency test
    pub const DISCRIMINANT_TABLE: &'static [(u8, &'static str)] = &[
        (0, "B16"),
        (1, "B21"),
        (2, "B26"),
        (4, "ABS_HI20"),
        (5, "SI14"),
        (7, "SI12"),
        (8, "PCALA_LO12"),
        (13, "PCALA_HI20"),
        (14, "PCADD_SHIFT2"),
        (15, "PCADD_SHIFT12"),
        (16, "PCADD_SHIFT18"),
        (17, "SPLIT_PCALA"),
        (18, "SPLIT_CALL30"),
        (19, "SPLIT_CALL36"),
        (9, "LITERAL8"),
        (10, "LITERAL16"),
        (11, "LITERAL32"),
        (12, "LITERAL64"),
    ];

    pub fn to_id(self) -> u8 {
        self as u8
    }

    pub fn size(self) -> u8 {
        match self {
            Relocation::LITERAL8 => 1,
            Relocation::LITERAL16 => 2,
            Relocation::B16
            | Relocation::B21
            | Relocation::B26
            | Relocation::LITERAL32
            | Relocation::ABS_HI20
            | Relocation::SI14
            | Relocation::SI12
            | Relocation::PCALA_LO12
            | Relocation::PCALA_HI20
            | Relocation::PCADD_SHIFT2
            | Relocation::PCADD_SHIFT12
            | Relocation::PCADD_SHIFT18 => 4,
            Relocation::SPLIT_PCALA | Relocation::SPLIT_CALL30 | Relocation::SPLIT_CALL36 => 8,
            Relocation::LITERAL64 => 8,
        }
    }
}

#[derive(Debug, Clone, Copy)]
pub struct Opdata {
    /// The base template for the encoding
    pub template: Template,
    /// What ISA targets this op is valid for
    pub isa_flags: ISAFlags,
    /// What extensions are required for this instruction
    pub ext_flags: &'static [ExtensionFlags],
    /// Matchers for instruction arguments
    pub matchers: &'static [Matcher],
    /// Encoder commands
    pub commands: &'static [Command],
}

macro_rules! SingleOp {
    ( $base:expr, [ $( $matcher:expr ),* ], [ $( $command:expr ),* ] ) => {
        {
            const MATCHERS: &'static [Matcher] = {
                #[allow(unused_imports)]
                use self::Matcher::*;
                &[ $(
                    $matcher
                ),* ]
            };
            const COMMANDS: &'static [Command] = {
                #[allow(unused_imports)]
                use self::Command::*;
                &[ $(
                    $command
                ),* ]
            };

            use self::Template::*;
            Opdata {
                isa_flags: ISAFlags::make(0),
                ext_flags: &[ExtensionFlags::Ex_BASE],
                template: $base,
                matchers: MATCHERS,
                commands: COMMANDS,
            }
        }
    }
}

macro_rules! Ops {
    // Single template: "name" = [ Single(template) , [matchers] => [commands]; ]
    ( $( $name:tt = [ $( $base:expr , [ $( $matcher:expr ),* ] => [ $( $command:expr ),* ] ; )+ ] )* ) => {
        [ $(
            (
                $name,
                &[ $(
                    SingleOp!( $base, [ $( $matcher ),* ], [ $( $command ),* ] )
                ),+ ] as &[_]
            )
        ),* ]
    }
}

/// Extended version of Ops! macro that supports Single, Double, and Many templates.
/// Used for pseudo-instructions that need multi-instruction templates.
/// Each entry takes: template, isa_flags_bits, ext_flags_slice, matchers, commands
macro_rules! PseudoOps {
    ( $( $name:tt = [ $( $template:expr , $isa_bits:expr , $ext:expr , [ $( $matcher:expr ),* ] => [ $( $command:expr ),* ] ; )+ ] )* ) => {
        [ $(
            (
                $name,
                &[ $(
                    {
                        const MATCHERS: &'static [Matcher] = {
                            #[allow(unused_imports)]
                            use self::Matcher::*;
                            &[ $(
                                $matcher
                            ),* ]
                        };
                        const COMMANDS: &'static [Command] = {
                            #[allow(unused_imports)]
                            use self::Command::*;
                            &[ $(
                                $command
                            ),* ]
                        };
                        Opdata {
                            isa_flags: ISAFlags::from_bits_truncate($isa_bits),
                            ext_flags: $ext,
                            template: $template,
                            matchers: MATCHERS,
                            commands: COMMANDS,
                        }
                    }
                ),+ ] as &[_]
            )
        ),* ]
    }
}

pub fn get_mnemonic_data(name: &str) -> Option<&'static [Opdata]> {
    OPMAP.get(&name).cloned()
}

#[allow(dead_code)]
pub fn mnemonics() -> hash_map::Keys<'static, &'static str, &'static [Opdata]> {
    OPMAP.keys()
}

lazy_static! {
    static ref OPMAP: HashMap<&'static str, &'static [Opdata]> = {
        use self::Relocation::*;
        use self::Template::*;
        use self::Matcher::*;
        use self::Command::*;

        static MAP: &[(&str, &[Opdata])] = &include!("opmap.rs");

        // Pseudo-instructions (generated by gen-opmap, not from opcode database)
        static PSEUDO_MAP: &[(&str, &[Opdata])] = &include!("pseudo_opmap.rs");

        let mut map: HashMap<&str, &[Opdata]> = MAP.iter().cloned().collect();
        for (name, data) in PSEUDO_MAP.iter() {
            map.insert(name, data);
        }
        map
    };
}