// This file was generated by tools/loongarch_gen_opmap
// Pseudo-instructions (not from opcode database, hand-coded)
// DO NOT EDIT MANUALLY — changes will be overwritten by gen-opmap

PseudoOps!(
    "la" = [
        Double(0x1A000000, 0x02C00000) ,
        0x03 , &[ExtensionFlags::Ex_BASE] ,
        [R, Offset] => [R(0), Repeat, R(5+32), Offset(SPLIT_PCALA)] ;
    ]
    "la.local" = [
        Double(0x1A000000, 0x02C00000) ,
        0x03 , &[ExtensionFlags::Ex_BASE] ,
        [R, Offset] => [R(0), Repeat, R(5+32), Offset(SPLIT_PCALA)] ;
    ]
    "call36" = [
        Double(0x1E000001, 0x4C000021) ,
        0x02 , &[ExtensionFlags::Ex_BASE] ,
        [Offset] => [Offset(SPLIT_CALL36)] ;
    ]
    "call30" = [
        Double(0x1C000001, 0x4C000021) ,
        0x03 , &[ExtensionFlags::Ex_BASE] ,
        [Offset] => [Offset(SPLIT_CALL30)] ;
    ]
    "tail36" = [
        Double(0x1E000000, 0x4C000000) ,
        0x02 , &[ExtensionFlags::Ex_BASE] ,
        [R, Offset] => [R(0), Offset(SPLIT_CALL36), R(5+32)] ;
    ]
    "tail30" = [
        Double(0x1C000000, 0x4C000000) ,
        0x03 , &[ExtensionFlags::Ex_BASE] ,
        [R, Offset] => [R(0), Offset(SPLIT_CALL30), R(5+32)] ;
    ]
    "li.w" = [
        Double(0x14000000, 0x03800000) ,
        0x03 , &[ExtensionFlags::Ex_BASE] ,
        [R, Imm] => [Rno0(0), Repeat, R(0+32), Repeat, R(5+32), LiW32] ;
    ]
    "li.d" = [
        Many(&[0x14000000, 0x03800000, 0x16000000, 0x03000000]) ,
        0x02 , &[ExtensionFlags::Ex_BASE] ,
        [R, Imm] => [Rno0(0), Repeat, R(0+32), Repeat, R(5+32), Repeat, R(0+64), Repeat, R(0+96), Repeat, R(5+96), LiD64] ;
    ]
)
