package main

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/loongson-community/loongarch-opcodes/scripts/go/common"
)

func main() {
	if len(os.Args) < 3 {
		fmt.Println("Usage: loongarch_gen_opmap <input-dir> <output-file>")
		os.Exit(1)
	}

	inputDir := os.Args[1]
	outputFile := os.Args[2]

	// 1. 读取并解析所有指令定义文件
	inputs, err := filepath.Glob(inputDir + "/*.txt")
	if err != nil {
		panic(err)
	}

	descs, err := common.ReadInsnDescs(inputs)
	if err != nil {
		panic(err)
	}

	// 2. 生成opmap.rs文件
	if err := generateOpmapFile(outputFile, descs); err != nil {
		fmt.Printf("Error generating opmap.rs: %v\n", err)
		os.Exit(1)
	}
}

// generateOpmapFile 生成opmap.rs文件
func generateOpmapFile(path string, insns []*common.InsnDescription) error {
	file, err := os.Create(path)
	if err != nil {
		return err
	}
	defer file.Close()

	// 写入文件头
	file.WriteString("// This file was generated by tools/loongarch_gen_opmap\n")
	file.WriteString("Ops!(\n\n")

	// 按助记符分组
	insnMap := make(map[string][]*common.InsnDescription)
	for _, insn := range insns {
		insnMap[insn.Mnemonic] = append(insnMap[insn.Mnemonic], insn)
	}

	// 按助记符排序
	var mnemonics []string
	for m := range insnMap {
		mnemonics = append(mnemonics, m)
	}
	sort.Strings(mnemonics)

	// 生成每条指令的条目
	for _, mnemonic := range mnemonics {
		group := insnMap[mnemonic]
		file.WriteString(fmt.Sprintf("\"%s\" = [\n", mnemonic))

		// 检查是否需要显示原始名称
		showOrigName := false
		for _, insn := range group {
			if origName, ok := insn.Attribs["orig_name"]; ok && origName != mnemonic {
				showOrigName = true
				break
			}
		}

		// 生成每个编码变体
		for _, insn := range group {
			if showOrigName {
				if origName, ok := insn.Attribs["orig_name"]; ok {
					file.WriteString(fmt.Sprintf("    // orig_name: %s\n", origName))
				}
			}

			// 格式化编码为0bxxxx_xxxx_xxxx_xxxx，确保32位
			bits := fmt.Sprintf("%032b", insn.Word)
			if len(bits) != 32 {
				return fmt.Errorf("invalid instruction word length: %d", len(bits))
			}
			formattedBits := fmt.Sprintf("0b%s_%s_%s_%s",
				bits[0:8], bits[8:16], bits[16:24], bits[24:32])

			// 生成操作数列表
			var argList []string
			for _, arg := range insn.Format.Args {
				argList = append(argList, argToRust(arg))
			}

			// 生成处理器列表
			var procList []string
			for _, arg := range insn.Format.Args {
				procList = append(procList, argToProcessor(arg))
			}

			file.WriteString(fmt.Sprintf("    %s = [%s] => [%s];\n",
				formattedBits, strings.Join(argList, ", "), strings.Join(procList, ", ")))
		}

		file.WriteString("]\n\n")
	}

	file.WriteString(")\n")
	return nil
}

// argToRust 将操作数转换为Rust宏参数
func argToRust(arg *common.Arg) string {
	if arg == nil {
		return "Unknown"
	}

	switch arg.Kind {
	case common.ArgKindIntReg:
		return "R"
	case common.ArgKindFPReg:
		return "F"
	case common.ArgKindFCCReg:
		return "C"
	case common.ArgKindScratchReg:
		return "T"
	case common.ArgKindVReg:
		return "V"
	case common.ArgKindXReg:
		return "X"
	case common.ArgKindSignedImm:
		return "Imm"
	case common.ArgKindUnsignedImm:
		return "Imm"
	default:
		if len(arg.Slots) == 0 {
			return "Unknown"
		}
		if len(arg.Slots) == 1 {
			return "Imm"
			// 	// 简单立即数
			// 	prefix := "S"
			// 	if arg.Kind == common.ArgKindUnsignedImm {
			// 		prefix = "U"
			// 	}
			// 	return fmt.Sprintf("%sk%d", prefix, arg.Slots[0].Width)
			// } else {
			// 	// 复合立即数
			// 	var parts []string
			// 	for _, slot := range arg.Slots {
			// 		parts = append(parts, fmt.Sprintf("k%d", slot.Width))
			// 	}
			// 	return fmt.Sprintf("S%s", strings.Join(parts, ""))
		}
		return "Unknown"
	}
}

// argToProcessor 将操作数转换为处理器表达式
func argToProcessor(arg *common.Arg) string {
	if arg == nil {
		return "Unknown"
	}
	if len(arg.Slots) == 0 {
		return "Unknown"
	}

	switch arg.Kind {
	case common.ArgKindIntReg:
		return fmt.Sprintf("R(%d)", arg.Slots[0].Offset)
	case common.ArgKindFPReg:
		return fmt.Sprintf("F(%d)", arg.Slots[0].Offset)
	case common.ArgKindVReg:
		return fmt.Sprintf("V(%d)", arg.Slots[0].Offset)
	case common.ArgKindXReg:
		return fmt.Sprintf("X(%d)", arg.Slots[0].Offset)
	case common.ArgKindFCCReg:
		return fmt.Sprintf("C(%d)", arg.Slots[0].Offset)
	case common.ArgKindScratchReg:
		return fmt.Sprintf("T(%d)", arg.Slots[0].Offset)
	case common.ArgKindSignedImm:
		if len(arg.Slots) == 1 {
			return fmt.Sprintf("SImm(%d, %d)", arg.Slots[0].Offset, arg.Slots[0].Width)
		} else {
			var parts []string
			for _, slot := range arg.Slots {
				parts = append(parts, fmt.Sprintf("%d, %d", slot.Offset, slot.Width))
			}
			return fmt.Sprintf("Sfields(&[%s])", strings.Join(parts, ", "))
		}
	case common.ArgKindUnsignedImm:
		if len(arg.Slots) == 1 {
			return fmt.Sprintf("UImm(%d, %d)", arg.Slots[0].Offset, arg.Slots[0].Width)
		} else {
			var parts []string
			for _, slot := range arg.Slots {
				parts = append(parts, fmt.Sprintf("%d, %d", slot.Offset, slot.Width))
			}
			return fmt.Sprintf("Ufields(&[%s])", strings.Join(parts, ", "))
		}
	default:
		return "Unknown"
	}
}
