package main

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/loongson-community/loongarch-opcodes/scripts/go/common"
)

type InsnDescription struct {
	Word       uint32
	Mnemonic   string
	Format     *InsnFormat
	OrigFormat *InsnFormat
	Attribs    map[string]string
}

type InsnFormat struct {
	Args []*Arg
}

type Arg struct {
	Kind  ArgKind
	Slots []*Slot
	Post  PostprocessOp
}

type Slot struct {
	Offset uint
	Width  uint
}

type PostprocessOp struct {
	Kind   PostprocessOpKind
	Amount int
}

type PostprocessOpKind int

const (
	PostprocessOpKindNone PostprocessOpKind = 0
	PostprocessOpKindAdd  PostprocessOpKind = 1
	PostprocessOpKindShl  PostprocessOpKind = 2
)

type ArgKind int

const (
	ArgKindUnknown     ArgKind = 0
	ArgKindIntReg      ArgKind = 1
	ArgKindFPReg       ArgKind = 2
	ArgKindFCCReg      ArgKind = 3
	ArgKindScratchReg  ArgKind = 4
	ArgKindVReg        ArgKind = 5
	ArgKindXReg        ArgKind = 6
	ArgKindSignedImm   ArgKind = 7
	ArgKindUnsignedImm ArgKind = 8
	ArgKindOffsetSI20  ArgKind = 9
	ArgKindRefOffset   ArgKind = 10
	ArgKindRefLabel    ArgKind = 11
	ArgKindOffsetSI14  ArgKind = 12
	ArgKindOffsetSI12  ArgKind = 13
	ArgKindOffsetSI16  ArgKind = 14
)

func main() {
	if len(os.Args) < 3 {
		fmt.Println("Usage: loongarch_gen_opmap <input-dir> <output-file>")
		os.Exit(1)
	}

	inputDir := os.Args[1]
	outputFile := os.Args[2]

	// 1. 读取并解析所有指令定义文件
	inputs, err := filepath.Glob(inputDir + "/*.txt")
	if err != nil {
		panic(err)
	}

	commonDescs, err := common.ReadInsnDescs(inputs)
	if err != nil {
		panic(err)
	}

	// 转换 common.InsnDescription 到本地 InsnDescription
	var descs []InsnDescription
	for _, d := range commonDescs {
		descs = append(descs, InsnDescription{
			Word:       d.Word,
			Mnemonic:   d.Mnemonic,
			Format:     convertFormat(d.Format),
			OrigFormat: convertFormat(d.OrigFormat),
			Attribs:    d.Attribs,
		})
	}

	// 2. 对特定指令进行特殊处理
	descs = processSpecialInstructions(descs)

	// 3. 生成opmap.rs文件
	if err := generateOpmapFile(outputFile, descs); err != nil {
		fmt.Printf("Error generating opmap.rs: %v\n", err)
		os.Exit(1)
	}
}

// generateOpmapFile 生成opmap.rs文件
func generateOpmapFile(path string, insns []InsnDescription) error {
	file, err := os.Create(path)
	if err != nil {
		return err
	}
	defer file.Close()

	// 写入文件头
	file.WriteString("// This file was generated by tools/loongarch_gen_opmap\n")
	file.WriteString("Ops!(\n\n")

	// 按助记符分组
	insnMap := make(map[string][]InsnDescription)
	for _, insn := range insns {
		insnMap[insn.Mnemonic] = append(insnMap[insn.Mnemonic], insn)
	}

	// 按助记符排序
	var mnemonics []string
	for m := range insnMap {
		mnemonics = append(mnemonics, m)
	}
	sort.Strings(mnemonics)

	// 生成每条指令的条目
	for _, mnemonic := range mnemonics {
		group := insnMap[mnemonic]
		shouldSkip := false
		// 检查是否需要显示原始名称
		showOrigName := false
		for _, insn := range group {
			if _, ok := insn.Attribs["lbt"]; ok {
				shouldSkip = true
			}
			if origName, ok := insn.Attribs["orig_name"]; ok && origName != mnemonic {
				showOrigName = true
				mnemonic = origName
			}
		}
		if shouldSkip {
			continue // 忽略LBT指令，它们在opmap中不显示
		}
		file.WriteString(fmt.Sprintf("\"%s\" = [\n", mnemonic))

		// 生成每个编码变体
		for _, insn := range group {
			if showOrigName {
				if origName, ok := insn.Attribs["orig_name"]; ok {
					file.WriteString(fmt.Sprintf("    // orig_name: %s\n", origName))
				}
			}

			// 格式化编码为0bxxxx_xxxx_xxxx_xxxx，确保32位
			bits := fmt.Sprintf("%032b", insn.Word)
			if len(bits) != 32 {
				return fmt.Errorf("invalid instruction word length: %d", len(bits))
			}
			formattedBits := fmt.Sprintf("0b%s_%s_%s_%s",
				bits[0:8], bits[8:16], bits[16:24], bits[24:32])

			var args = insn.Format.Args

			if insn.OrigFormat != nil {
				args = insn.OrigFormat.Args
			}
			// 生成操作数列表
			var argList []string
			for idx, arg := range args {
				argList = append(argList, argToRust(mnemonic, idx, arg))
			}

			// 生成处理器列表
			var procList []string

			for idx, arg := range args {
				procList = append(procList, argToProcessor(mnemonic, idx, arg))
			}

			file.WriteString(fmt.Sprintf("    %s = [%s] => [%s];\n",
				formattedBits, strings.Join(argList, ", "), strings.Join(procList, ", ")))
		}

		file.WriteString("]\n\n")
	}

	file.WriteString(")\n")
	return nil
}

// argToRust 将操作数转换为Rust宏参数
func argToRust(mnemonic string, idx int, arg *Arg) string {
	if arg == nil {
		return "Unknown"
	}

	switch arg.Kind {
	case ArgKindIntReg:
		if (mnemonic == "movfcsr2gr" || mnemonic == "movgr2fcsr") &&
			idx == 1 {
			return "FCSR"
		} else {
			return "R"
		}
	case ArgKindFPReg:
		return "F"
	case ArgKindFCCReg:
		return "C"
	case ArgKindScratchReg:
		return "T"
	case ArgKindVReg:
		return "V"
	case ArgKindXReg:
		return "X"
	case ArgKindSignedImm, ArgKindUnsignedImm:
		return "Imm"
	case ArgKindOffsetSI20, ArgKindOffsetSI12, ArgKindOffsetSI14, ArgKindOffsetSI16:
		return "Offset"

	default:
		if len(arg.Slots) == 0 {
			return "Unknown"
		}
		if len(arg.Slots) == 1 {
			return "Imm"
		}
		return "Unknown"
	}
}

// convertFormat 转换 common.InsnFormat 到本地 InsnFormat
func convertFormat(f *common.InsnFormat) *InsnFormat {
	if f == nil {
		return nil
	}
	var args []*Arg
	for _, a := range f.Args {
		args = append(args, &Arg{
			Kind:  ArgKind(a.Kind),
			Slots: convertSlots(a.Slots),
			Post:  convertPost(a.Post),
		})
	}
	return &InsnFormat{Args: args}
}

func copyFormat(f *InsnFormat) *InsnFormat {
	if f == nil {
		return nil
	}
	var args []*Arg
	for _, a := range f.Args {
		args = append(args, &Arg{
			Kind:  ArgKind(a.Kind),
			Slots: copySlots(a.Slots),
			Post:  copyPost(a.Post),
		})
	}
	return &InsnFormat{Args: args}
}

// convertSlots 转换 common.Slot 到本地 Slot
func copySlots(slots []*Slot) []*Slot {
	var result []*Slot
	for _, s := range slots {
		result = append(result, &Slot{
			Offset: s.Offset,
			Width:  s.Width,
		})
	}
	return result
}

// convertPost 转换 common.PostprocessOp 到本地 PostprocessOp
func copyPost(p PostprocessOp) PostprocessOp {
	return PostprocessOp{
		Kind:   PostprocessOpKind(p.Kind),
		Amount: p.Amount,
	}
}

// convertSlots 转换 common.Slot 到本地 Slot
func convertSlots(slots []*common.Slot) []*Slot {
	var result []*Slot
	for _, s := range slots {
		result = append(result, &Slot{
			Offset: s.Offset,
			Width:  s.Width,
		})
	}
	return result
}

// convertPost 转换 common.PostprocessOp 到本地 PostprocessOp
func convertPost(p common.PostprocessOp) PostprocessOp {
	return PostprocessOp{
		Kind:   PostprocessOpKind(p.Kind),
		Amount: p.Amount,
	}
}

// processSpecialInstructions 处理特定指令的参数类型
func processSpecialInstructions(descs []InsnDescription) []InsnDescription {
	// offset_insn := map[string]bool{
	// 	"pcaddi":    true,
	// 	"pcaddu12i": true,
	// 	"pcaddu18i": true,
	// 	"pcalau12i": true,
	// 	"beq":       true,
	// 	"bne":       true,
	// 	"blt":       true,
	// 	"bge":       true,
	// 	"bltu":      true,
	// 	"bgeu":      true,
	// 	"beqz":      true,
	// 	"bnez":      true,
	// 	"b":         true,
	// 	"bl":        true,
	// 	"jirl":      true,
	// 	"bceqz":     true,
	// 	"bcnez":     true,
	// }

	// for i := range descs {
	// 	desc := &descs[i]
	// 	mnemonic := desc.Mnemonic
	// 	if origName, ok := desc.Attribs["orig_name"]; ok && origName != desc.Mnemonic {
	// 		mnemonic = origName
	// 	}

	// 	if !offset_insn[mnemonic] {
	// 		continue
	// 	}

	// 	format := desc.OrigFormat
	// 	if format == nil {
	// 		format = desc.Format
	// 	}
	// 	if format == nil {
	// 		continue
	// 	}
	// 	desc.Format = format
	// 	for _, arg := range format.Args {
	// 		if arg.Kind == ArgKindSignedImm {
	// 			arg.Kind = ArgKindOffsetSI20
	// 		}
	// 	}
	// }

	load_store_insn := map[string]ArgKind{
		"ld.b":  ArgKindOffsetSI12,
		"ld.d":  ArgKindOffsetSI12,
		"ld.h":  ArgKindOffsetSI12,
		"ld.w":  ArgKindOffsetSI12,
		"st.b":  ArgKindOffsetSI12,
		"st.h":  ArgKindOffsetSI12,
		"st.w":  ArgKindOffsetSI12,
		"st.d":  ArgKindOffsetSI12,
		"ld.bu": ArgKindOffsetSI12,
		"ld.du": ArgKindOffsetSI12,
		"ld.hu": ArgKindOffsetSI12,
		"ld.wu": ArgKindOffsetSI12,
		"st.bu": ArgKindOffsetSI12,
		"st.hu": ArgKindOffsetSI12,
		"st.wu": ArgKindOffsetSI12,
		"st.du": ArgKindOffsetSI12,
		"fld.s": ArgKindOffsetSI12,
		"fld.d": ArgKindOffsetSI12,
		"fst.s": ArgKindOffsetSI12,
		"fst.d": ArgKindOffsetSI12,

		"ll.w":    ArgKindOffsetSI14,
		"sc.w":    ArgKindOffsetSI14,
		"ll.d":    ArgKindOffsetSI14,
		"sc.d":    ArgKindOffsetSI14,
		"ldptr.w": ArgKindOffsetSI14,
		"stptr.w": ArgKindOffsetSI14,
		"ldptr.d": ArgKindOffsetSI14,
		"stptr.d": ArgKindOffsetSI14,

		"pcaddi":    ArgKindOffsetSI20,
		"pcaddu12i": ArgKindOffsetSI20,
		"pcaddu18i": ArgKindOffsetSI20,
		"pcalau12i": ArgKindOffsetSI20,
		"beq":       ArgKindOffsetSI20,
		"bne":       ArgKindOffsetSI20,
		"blt":       ArgKindOffsetSI20,
		"bge":       ArgKindOffsetSI20,
		"bltu":      ArgKindOffsetSI20,
		"bgeu":      ArgKindOffsetSI20,
		"beqz":      ArgKindOffsetSI20,
		"bnez":      ArgKindOffsetSI20,
		"b":         ArgKindOffsetSI20,
		"bl":        ArgKindOffsetSI20,
		"jirl":      ArgKindOffsetSI20,
		"bceqz":     ArgKindOffsetSI20,
		"bcnez":     ArgKindOffsetSI20,
	}

	var tmp_descs []InsnDescription

	for i := range descs {
		desc := &descs[i]
		mnemonic := desc.Mnemonic
		if origName, ok := desc.Attribs["orig_name"]; ok && origName != desc.Mnemonic {
			mnemonic = origName
		}
		_, ok := load_store_insn[mnemonic]
		if !ok {
			continue
		}

		tmp_descs = append(tmp_descs, InsnDescription{
			Word:       desc.Word,
			Mnemonic:   desc.Mnemonic,
			Format:     copyFormat(desc.Format),
			OrigFormat: copyFormat(desc.OrigFormat),
			Attribs:    desc.Attribs,
		})

		format := desc.OrigFormat
		if format == nil {
			format = desc.Format
		}

		for _, arg := range format.Args {
			if arg.Kind == ArgKindSignedImm {
				arg.Kind = load_store_insn[mnemonic]
			}
		}
	}

	descs = append(descs, tmp_descs...)
	return descs
}

// argToProcessor 将操作数转换为处理器表达式
func argToProcessor(mnemonic string, idx int, arg *Arg) string {
	if arg == nil {
		return "Unknown"
	}
	if len(arg.Slots) == 0 {
		return "Unknown"
	}

	insn_scaled := map[string]int{

		"ll.d": 2,
		"sc.d": 2,
		"ll.w": 2,
		"sc.w": 2,

		// "st.h": 1,
		// "st.w": 2,
		// "st.d": 3,

		// "ld.h":  1,
		// "ld.w":  2,
		// "ld.d":  3,
		// "ld.hu": 2,
		// "ld.wu": 2,

		"vldrepl.h":  1,
		"vstelm.h":   1,
		"xvldrepl.h": 1,
		"xvstelm.h":  1,

		// "pcaddi":    1,
		// "pcaddu12i": 2,
		// "pcaddu18i": 2,
		// "pcalau12i": 2,

		"ldptr.w": 2,
		"stptr.w": 2,
		"ldptr.d": 2,
		"stptr.d": 2,

		"vldrepl.w":  2,
		"vstelm.w":   2,
		"xvldrepl.w": 2,
		"xvstelm.w":  2,

		"vldrepl.d":  3,
		"vstelm.d":   3,
		"xvldrepl.d": 3,
		"xvstelm.d":  3,

		"beq":   2,
		"bne":   2,
		"blt":   2,
		"bge":   2,
		"bltu":  2,
		"bgeu":  2,
		"beqz":  2,
		"bnez":  2,
		"b":     2,
		"bl":    2,
		"jirl":  2,
		"bceqz": 2,
		"bcnez": 2,
	}

	switch arg.Kind {
	case ArgKindIntReg:
		if (mnemonic == "movfcsr2gr" || mnemonic == "movgr2fcsr") &&
			idx == 1 {
			return fmt.Sprintf("FCSR(%d)", arg.Slots[0].Offset)
		} else {
			return fmt.Sprintf("R(%d)", arg.Slots[0].Offset)
		}
	case ArgKindFPReg:
		return fmt.Sprintf("F(%d)", arg.Slots[0].Offset)
	case ArgKindVReg:
		return fmt.Sprintf("V(%d)", arg.Slots[0].Offset)
	case ArgKindXReg:
		return fmt.Sprintf("X(%d)", arg.Slots[0].Offset)
	case ArgKindFCCReg:
		return fmt.Sprintf("C(%d)", arg.Slots[0].Offset)
	case ArgKindScratchReg:
		return fmt.Sprintf("T(%d)", arg.Slots[0].Offset)
	case ArgKindSignedImm:
		scaled, ok := insn_scaled[mnemonic]
		if ok {
			return fmt.Sprintf("Sscaled(%d, %d, %d)", arg.Slots[0].Offset, arg.Slots[0].Width, scaled)
		}
		if len(arg.Slots) == 1 {
			return fmt.Sprintf("SImm(%d, %d)", arg.Slots[0].Offset, arg.Slots[0].Width)
		} else {
			var parts []string
			for _, slot := range arg.Slots {
				parts = append(parts, fmt.Sprintf("%d, %d", slot.Offset, slot.Width))
			}
			return fmt.Sprintf("Sfields(&[%s])", strings.Join(parts, ", "))
		}
	case ArgKindUnsignedImm:

		if mnemonic == "alsl.w" || mnemonic == "alsl.d" || mnemonic == "alsl.wu" {
			return fmt.Sprintf("Usubone(%d, %d)", arg.Slots[0].Offset, arg.Slots[0].Width)
		}
		if (mnemonic == "bstrins.d" || mnemonic == "bstrins.w" ||
			mnemonic == "bstrpick.d" || mnemonic == "bstrpick.w") &&
			idx == 3 {
			return fmt.Sprintf("Ulep(%d, %d)", arg.Slots[0].Offset, arg.Slots[0].Width)
		}
		if len(arg.Slots) == 1 {
			return fmt.Sprintf("UImm(%d, %d)", arg.Slots[0].Offset, arg.Slots[0].Width)
		} else {
			var parts []string
			for _, slot := range arg.Slots {
				parts = append(parts, fmt.Sprintf("%d, %d", slot.Offset, slot.Width))
			}
			return fmt.Sprintf("Ufields(&[%s])", strings.Join(parts, ", "))
		}
	case ArgKindOffsetSI20:
		// 特殊处理分支指令
		if mnemonic == "beq" || mnemonic == "bne" ||
			mnemonic == "blt" || mnemonic == "bge" ||
			mnemonic == "bltu" || mnemonic == "bgeu" ||
			mnemonic == "jirl" {
			return "Offset(B)"
		} else if mnemonic == "b" || mnemonic == "bl" {
			return "Offset(J)"
		} else if mnemonic == "beqz" || mnemonic == "bnez" ||
			mnemonic == "bceqz" || mnemonic == "bcnez" {
			return "Offset(BZ)"
		}
		return "Offset(SI20)"
	case ArgKindOffsetSI14:
		return "Offset(SI14)"
	case ArgKindOffsetSI12:
		return "Offset(SI12)"
	case ArgKindOffsetSI16:
		return "Offset(SI16)"
	default:
		return "Unknown"
	}
}
